name: Continuous integration
on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch: # allows manual triggering
env:
  # Bump this number to invalidate the GH actions cache
  cache-version: 0

jobs:
  build:
    strategy:
      matrix:
        name: ['trilby']
        edition: ['server']
        release: ['unstable']
        hostArch: ['aarch64']
        format: ['isoImage']
    runs-on: 'ubuntu-latest'
    name: ${{ matrix.name }}-${{ matrix.edition }}-${{ matrix.release }}-${{ matrix.hostArch }}-${{ matrix.format }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
    - uses: cachix/cachix-action@v12
      with:
        name: trilby
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build
      run: |
        nix build \
          --accept-flake-config \
          --print-build-logs \
          .#${{ matrix.name }}-${{ matrix.edition }}-${{ matrix.release }}-${{ matrix.hostArch }}-${{ matrix.format }}
    - run: echo "UPLOAD_PATH=$(readlink -f result)" >> $GITHUB_ENV
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: result
        path: ${{ env.UPLOAD_PATH }}
